### ISSUE TITLE
Contents of tarball do not match README

### ISSUE THREAD

**Issue by elafargue** [habeIchVergessen/GL-X3000#1]
It looks like the tarball that is included in this repository is not in sync with the instructions. In particular, the `scripts` directory is missing.

Also, all the directories in the archive start with a "." for some reason, making the files hidden by default, which is probably not the desired outcome?

Last, is there a good reason why you are including the files as a "tgz" archive, rather than simply put them in the git repo directly?

```
# tar xvzf /tmp/GL-X3000\%20gpx.tgz
.config/
.config/etc/
.config/etc/nginx/
.config/etc/nginx/gl-conf.d/
.config/etc/nginx/gl-conf.d/service-gps.conf
.config/etc/php.ini
.config/etc/init.d/
.config/etc/init.d/gpsd
.config/etc/php8-fpm.conf
.config/etc/php8-fpm.d/
.config/etc/php8-fpm.d/gps.conf
.cron/
.cron/crontab
.gps/
.uci/
.uci/gpsd.uci
.www/
.www/upload/
.www/upload/upload.php
.www/certs/
.www/gps/
.www/gps/css/
.www/gps/css/gps.css
.www/gps/index.php
.www/gps/GpxClasses.php
.www/gps/js/
.www/gps/js/gps.js
.www/gps/RemoteConfig.php
.www/gps/LocalConfig.php
```

**Comment by habeIchVergessen** [comment]
added scripts directory

**Comment by habeIchVergessen** [comment]
file permissions are the reason for tar ball.
just my flavour using directory names with starting dot
